version: '3.8'

services:
  #Trạm trung chuyển Redis
  redis:
    image: redis:alpine
    container_name: batxat_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Backend Spring Boot (Nằm trong thư mục hiện tại/GuardBatXat)
  backend:
    build:
      context: ./GuardBatXat
      dockerfile: Dockerfile
    container_name: batxat_backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/guard_bat_xat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: unless-stopped

  # Module AI Inference - Chạy Bước 06 (Nằm ở thư mục anh em)
  python-ai:
    build:
      context: ../GuardBaXat/Spatial-Intelligence
      dockerfile: Dockerfile
    container_name: batxat_ai_engine
    volumes:
      - ../GuardBaXat/Spatial-Intelligence/data:/app/data
      - ../GuardBaXat/Spatial-Intelligence/models:/app/models
    environment:
      - DB_HOST=host.docker.internal
      - DB_NAME=guard_bat_xat
      - DB_USER=postgres
      - DB_PASS=12345678
    command: python src/module2/06_inference.py
    restart: unless-stopped

  # Module Data Fusion - Chạy Bước 04 liên tục (Nằm ở thư mục anh em)
  python-worker:
    build:
      context: ../GuardBaXat/Spatial-Intelligence
    container_name: batxat_data_fusion
    volumes:
      - ../GuardBaXat/Spatial-Intelligence/data:/app/data
    environment:
      - DB_HOST=host.docker.internal
      - API_KEY_VC=97JQA9YSSKCDXW3HVV8CZDQB6
    command: python src/module1/04_data_fusion.py
    restart: always
  #Giao diện WebGIS Next.js
  frontend:
    build:
      context: ./batxat-client
      dockerfile: Dockerfile
    container_name: batxat_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./batxat-client:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    restart: unless-stopped