server:
  port: 8080
spring:
  application:
    name: GuardBatXat
  datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/GuardBatXat}
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:hieu040205}
      driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      database: 0
batxat:
  security:
    jwt:
      secret: ${JWT_SECRET:DayLaMotKhoaBaoMatCucKyDaiVaPhucTapCuaHeThongCanhBaoThienTaiBatXat2024!@#}
      expiration: 86400000