-- Canonical compatibility migration for both known GuardBatXat snapshots.
-- Flyway must baseline an existing restored database at version 0 before this runs.

-- Normalize role names without relying on conflicting numeric role IDs.
DO $$
DECLARE
    viewer_role_id integer;
    citizen_role_id integer;
BEGIN
    SELECT role_id INTO viewer_role_id
    FROM batxat_roles
    WHERE role_name = 'VIEWER';

    SELECT role_id INTO citizen_role_id
    FROM batxat_roles
    WHERE role_name = 'CITIZEN';

    IF viewer_role_id IS NOT NULL AND citizen_role_id IS NULL THEN
        UPDATE batxat_roles
        SET role_name = 'CITIZEN', description = 'Người dân'
        WHERE role_id = viewer_role_id;
    ELSIF viewer_role_id IS NOT NULL THEN
        UPDATE batxat_users
        SET role_id = citizen_role_id
        WHERE role_id = viewer_role_id;

        DELETE FROM batxat_roles
        WHERE role_id = viewer_role_id;
    END IF;
END
$$;

INSERT INTO batxat_roles (role_name, description)
SELECT required.role_name, required.description
FROM (VALUES
    ('CITIZEN', 'Người dân'),
    ('RESCUE_TEAM', 'Đội cứu hộ'),
    ('COMMANDER', 'Trung tâm chỉ huy'),
    ('ADMIN', 'Quản trị viên hệ thống')
) AS required(role_name, description)
WHERE NOT EXISTS (
    SELECT 1
    FROM batxat_roles existing
    WHERE existing.role_name = required.role_name
);

-- User fields required by the current backend.
ALTER TABLE batxat_users
    ADD COLUMN IF NOT EXISTS default_building_id bigint,
    ADD COLUMN IF NOT EXISTS trust_score numeric(3,2);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'batxat_users'::regclass
          AND conname = 'batxat_users_default_building_id_fkey'
    ) THEN
        ALTER TABLE batxat_users
            ADD CONSTRAINT batxat_users_default_building_id_fkey
            FOREIGN KEY (default_building_id) REFERENCES batxat_buildings(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'batxat_users'::regclass
          AND conname = 'batxat_users_trust_score_check'
    ) THEN
        ALTER TABLE batxat_users
            ADD CONSTRAINT batxat_users_trust_score_check
            CHECK (trust_score IS NULL OR trust_score BETWEEN 0 AND 1);
    END IF;
END
$$;

-- Risk features present in the newer dataset.
ALTER TABLE batxat_buildings
    ADD COLUMN IF NOT EXISTS landcover numeric(5,2) DEFAULT 0.5,
    ADD COLUMN IF NOT EXISTS slope numeric(5,2);

ALTER TABLE batxat_model_registry
    ADD COLUMN IF NOT EXISTS feat_imp_landcover double precision DEFAULT 0.0;

-- Incident reports are required by the current backend but absent locally.
CREATE TABLE IF NOT EXISTS batxat_incident_reports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id integer,
    reporter_name character varying(100),
    reporter_phone character varying(15),
    incident_type character varying(50) NOT NULL,
    impact_level character varying(20) NOT NULL,
    description text,
    images text,
    gps_lat double precision NOT NULL,
    gps_lng double precision NOT NULL,
    geom geometry(Point, 4326),
    status character varying(20) DEFAULT 'PENDING',
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'batxat_incident_reports'::regclass
          AND conname = 'batxat_incident_reports_reporter_id_fkey'
    ) THEN
        ALTER TABLE batxat_incident_reports
            ADD CONSTRAINT batxat_incident_reports_reporter_id_fkey
            FOREIGN KEY (reporter_id) REFERENCES batxat_users(user_id)
            ON DELETE SET NULL;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_incidents_geom
    ON batxat_incident_reports USING gist(geom);
CREATE INDEX IF NOT EXISTS idx_incidents_status
    ON batxat_incident_reports(status);

-- The local road-node geom column is obsolete and was verified empty.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'batxat_road_nodes'
          AND column_name = 'geom'
    ) THEN
        IF EXISTS (SELECT 1 FROM batxat_road_nodes WHERE geom IS NOT NULL) THEN
            RAISE EXCEPTION 'Cannot drop batxat_road_nodes.geom because it contains data';
        END IF;

        ALTER TABLE batxat_road_nodes DROP COLUMN geom;
    END IF;
END
$$;

ALTER TABLE batxat_road_nodes
    ALTER COLUMN node_id SET NOT NULL,
    ALTER COLUMN geometry SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'batxat_road_nodes'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE batxat_road_nodes
            ADD CONSTRAINT batxat_road_nodes_pkey PRIMARY KEY (node_id);
    END IF;
END
$$;

-- Normalize pandas-created bigint metadata columns to the Java/domain contract.
ALTER TABLE batxat_road_edges
    ALTER COLUMN key TYPE integer USING key::integer,
    ALTER COLUMN road_capacity TYPE integer USING road_capacity::integer,
    ALTER COLUMN is_bridge TYPE integer USING is_bridge::integer,
    ALTER COLUMN community_report TYPE integer USING community_report::integer,
    ALTER COLUMN cost_safety TYPE double precision USING cost_safety::double precision,
    ALTER COLUMN cost_speed TYPE double precision USING cost_speed::double precision,
    ALTER COLUMN u SET NOT NULL,
    ALTER COLUMN v SET NOT NULL,
    ALTER COLUMN key SET NOT NULL,
    ALTER COLUMN geometry SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'batxat_road_edges'::regclass
          AND contype = 'p'
    ) THEN
        ALTER TABLE batxat_road_edges
            ADD CONSTRAINT batxat_road_edges_pkey PRIMARY KEY (u, v, key);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'batxat_road_edges'::regclass
          AND conname = 'batxat_road_edges_u_fkey'
    ) THEN
        ALTER TABLE batxat_road_edges
            ADD CONSTRAINT batxat_road_edges_u_fkey
            FOREIGN KEY (u) REFERENCES batxat_road_nodes(node_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'batxat_road_edges'::regclass
          AND conname = 'batxat_road_edges_v_fkey'
    ) THEN
        ALTER TABLE batxat_road_edges
            ADD CONSTRAINT batxat_road_edges_v_fkey
            FOREIGN KEY (v) REFERENCES batxat_road_nodes(node_id);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_batxat_road_edges_u ON batxat_road_edges(u);
CREATE INDEX IF NOT EXISTS idx_batxat_road_edges_v ON batxat_road_edges(v);

-- Validate AHP values while allowing the existing five-decimal rounding.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'batxat_ahp_weights'::regclass
          AND conname = 'batxat_ahp_weights_range_check'
    ) THEN
        ALTER TABLE batxat_ahp_weights
            ADD CONSTRAINT batxat_ahp_weights_range_check CHECK (
                w_distance BETWEEN 0 AND 1 AND
                w_flood BETWEEN 0 AND 1 AND
                w_landslide BETWEEN 0 AND 1 AND
                w_capacity BETWEEN 0 AND 1 AND
                w_bridge BETWEEN 0 AND 1 AND
                w_report BETWEEN 0 AND 1
            );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'batxat_ahp_weights'::regclass
          AND conname = 'batxat_ahp_weights_sum_check'
    ) THEN
        ALTER TABLE batxat_ahp_weights
            ADD CONSTRAINT batxat_ahp_weights_sum_check CHECK (
                abs((w_distance + w_flood + w_landslide + w_capacity + w_bridge + w_report)::double precision - 1.0) <= 0.001
            );
    END IF;
END
$$;

-- Recreate the routing function after normalizing the edge key/cost types.
DROP FUNCTION IF EXISTS get_daily_routing_costs(character varying);

CREATE FUNCTION get_daily_routing_costs(p_strategy character varying)
RETURNS TABLE(
    u bigint,
    v bigint,
    key integer,
    final_cost double precision,
    risk_level character varying
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_f_risk double precision;
    v_l_risk double precision;
    v_w record;
BEGIN
    SELECT
        COALESCE(flood_risk_pct / 100, 0.5)::double precision,
        COALESCE(landslide_risk_pct / 100, 0.5)::double precision
    INTO v_f_risk, v_l_risk
    FROM batxat_daily_risk
    WHERE forecast_date = CURRENT_DATE;

    IF v_f_risk IS NULL THEN
        v_f_risk := 0.5;
        v_l_risk := 0.5;
    END IF;

    SELECT * INTO v_w
    FROM batxat_ahp_weights
    WHERE strategy_name = p_strategy;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Unknown routing strategy: %', p_strategy;
    END IF;

    RETURN QUERY
    SELECT
        e.u,
        e.v,
        e.key,
        (
            COALESCE(v_w.w_distance, 0)::double precision * e.length_m +
            COALESCE(v_w.w_flood, 0)::double precision * (v_f_risk * (1000 / (e.avg_elevation + 1)) * 10000) +
            COALESCE(v_w.w_landslide, 0)::double precision * (v_l_risk * (e.avg_slope / 35.0) * 15000) +
            COALESCE(v_w.w_capacity, 0)::double precision * (e.road_capacity * 1000) +
            COALESCE(v_w.w_bridge, 0)::double precision * (e.is_bridge * 5000) +
            COALESCE(v_w.w_report, 0)::double precision * (e.community_report * 20000)
        )::double precision AS final_cost,
        CASE
            WHEN (v_l_risk * (e.avg_slope / 35.0)) > 0.7 THEN 'CỰC KỲ NGUY HIỂM'
            WHEN (v_f_risk * (1000 / (e.avg_elevation + 1))) > 0.5 THEN 'NGUY CƠ NGẬP'
            ELSE 'ỔN ĐỊNH'
        END::character varying AS risk_level
    FROM batxat_road_edges e;
END;
$$;
